### PR TITLE
Prediction script 

### PR DESCRIPTION
**Pull request by shahrukhqasim**

### CODE REVIEW

**Comment by jkiesele** [comment]
Can you please give some more hints what this is?
a) Why is there a model in there?
b) Why don't you use the predict pipeline in DJC? You are reinventing the wheel in many places here.
c) I would recommend to have plotting and beta selection functionality as external functions so we can re-use them and slowly build a set of plots that we can just use in a plug and play manner.

**Comment by shahrukhqasim** [comment]
I have fixed most of the problems except c. It is coming.

**Comment by shahrukhqasim** [comment]
Also added functionality to produce a single pdf file with multiple plots.

**Comment by jkiesele** [comment]
Thanks for the changes, looks much better.
You can add the plotting part as individual functions to:
https://github.com/cms-pepr/HGCalML/blob/master/modules/ragged_plotting_tools.py
Please indicate exactly how the input is supposed to be shaped.

We also need to merge the two implementations that select the representative vertices. But this can be a second PR. 

For now, the only remaining request is that you rename the variables to something that is more physical. E.g. we neither have labels nor do we have classes (for now). We have truth shower indices / assignments, condensation points etc. If we don't have some sort of semi-homogenous naming scheme, it is very easy to get confused.

**Pull request merged**
