### PR TITLE
[WIP] Slicing kNN

### PR DESCRIPTION
**Pull request by oviazlo**
- kernel performs kNN search with including coordinate sorting inside the kernel
- the goal is to substitute the original select_knn kernel
- problem with memory management is fixed (that was reported last time)
- was tested up to 200k vertices and up to 400 2d bins
- script for performance comparison of kNN kernels is included

### CODE REVIEW

**Comment by oviazlo** [comment]
1) Allocate memory with TF means:
https://github.com/cms-pepr/HGCalML/blob/master/modules/compiled/latent_space_grid_kernel.cc#L390
2) Search for min and max with TF means (and pass it as an argument to the kernel)
3) Do sorting in TF as well (and pass it to the kernel) - low priority
4) remove unnecessary cudaDeviceSynchronize (e.g. l.693-702)
5) calculate GPU memory usage for each auxiliary matrix
6) gradient: https://github.com/cms-pepr/HGCalML/blob/master/modules/select_knn_op.py#L74-L83

**Comment by oviazlo** [comment]
- default values for n_bins_x = n_bins_y = 40
- finish unit-test (simple ones)

**Comment by oviazlo** [comment]
Open questions:

1. how to test the correctness of the gradient calculation?

**Comment by oviazlo** [comment]
"kernel is crushing with 300k of vertices input and 400 bins (at 1080 gpu). Probably out of GPU memory. To be investigated."
--> 
The problem was in the function where I calculate recall and it is NOT related to kNN kernel. 
I have tested to run a kernel on 1M of vertices - no problems.

**Comment by oviazlo** [comment]
Hi @jkiesele 
I agree about the name. I've changed it to the one you suggested. Do you want me to squash all commits to one (to have only one comment in the git log)?

**Comment by jkiesele** [comment]
Cool :)
No worries about the commits!

Am 21/09/2021 um 18:53 schrieb Oleksandr Viazlo ***@***.***>:

﻿

Hi @jkiesele<https://github.com/jkiesele>
I agree about the name. I've changed it to the one you suggested. Do you want me to squash all commits to one (to have only one comment in the git log)?

**Comment by oviazlo** [comment]
I've squashed all commits to one to simplify merging to master.

**Pull request merged**
